pipelines:
  pull-requests:
    '**':
      - step:
          name: Build artifact
          caches:
            - composer
          image: php:8.2-cli
          script:
# Add DDEV’s GPG key to your keyring
            - sudo sh -c 'echo ""'
            - sudo apt-get update && sudo apt-get install -y curl
            - sudo install -m 0755 -d /etc/apt/keyrings
            - curl -fsSL https://pkg.ddev.com/apt/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/ddev.gpg > /dev/null
            - sudo chmod a+r /etc/apt/keyrings/ddev.gpg

            # Add DDEV releases to your package repository
            - sh -c 'echo ""'
            - echo "deb [signed-by=/etc/apt/keyrings/ddev.gpg] https://pkg.ddev.com/apt/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list >/dev/null

            # Update package information and install DDEV
            - sudo sh -c 'echo ""'
            - sudo apt-get update && sudo apt-get install -y ddev

            # One-time initialization of mkcert
            - mkcert -install
            - ddev --version
            - 
            # Firstly, install composer and required libraries.
            - apt-get update -yqq
            - apt-get install -y wget git zip unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - export COMPOSER_ALLOW_SUPERUSER=1
            # Secondly, install the project while ignoring PHP extensions like "bcmath" or "gd".
            # Ignore dev dependencies if drupal-check is already there.
            # While using Acquia Cloud, disable the BLT plugin.
            # - composer config allow-plugins.acquia/blt false
            - composer install --no-dev --ignore-platform-req=ext-*
          artifacts:
            # The entire project directory will be passed to next steps.
            - "**"

      - parallel:
          steps:
            - step:
                name: CodeSniffer
                image: droptica/phpcs
                script:
                  - phpcs  --standard=./phpcs.xml ./web/modules/custom ./web/themes/custom
                  # - phpcs --standard=PSR12 --extensions=php,yml --report=full,gitblame ./tests

            - step:
                name: PHPStan
                image: droptica/phpstan
                script:
                  # Workaround for phpstan.neon absolute paths.
                  - ln -s "$(pwd)" /opt/project
                  - phpstan analyse -c ./phpstan.neon --no-progress
