definitions:
  services:
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_DATABASE: 'drupal'
        MYSQL_ROOT_PASSWORD: 'root'

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build and Test Drupal
          image: drupal:10-apache
          services:
            - mysql
          caches:
            - composer
          script:
            # Instalacja niezbędnych narzędzi
            - apt-get update && apt-get install -y git unzip

            # Instalacja Composera
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            
            # Instalacja zależności projektu
            - composer install --no-dev --ignore-platform-req=ext-*
            
            # Instalacja Drush
            - composer require drush/drush
            
            # Konfiguracja Drupala
            - mkdir -p web/sites/default/files
            - chmod -R 777 web/sites/default/files
            - cp web/sites/default/default.settings.php web/sites/default/settings.php
            - chmod 777 web/sites/default/settings.php
            
            # Konfiguracja bazy danych
            - echo "\$databases['default']['default'] = ['driver' => 'mysql','database' => 'drupal','username' => 'root','password' => 'root','host' => 'mysql'];" >> web/sites/default/settings.php
            
            # Instalacja Drupala
            - vendor/bin/drush site:install --account-name=admin --account-pass=admin -y
            
            # Sprawdzenie statusu
            - vendor/bin/drush status
            
            # Opcjonalnie: import konfiguracji
            # - vendor/bin/drush cim -y
          artifacts:
            - "**"

      - parallel:
          steps:
            - step:
                name: CodeSniffer
                image: droptica/phpcs
                script:
                  - phpcs --standard=./phpcs.xml ./web/modules/custom ./web/themes/custom

            - step:
                name: PHPStan
                image: droptica/phpstan
                script:
                  - ln -s "$(pwd)" /opt/project
                  - phpstan analyse -c ./phpstan.neon --no-progress
