definitions:
  services:
    docker:
      memory: 3072  # Zwiększamy pamięć dla Docker

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build artifact
          caches:
            - composer
          image: php:8.2-cli
          script:
            # Instalacja composera i wymaganych bibliotek
            - apt-get update -yqq
            - apt-get install -y wget git zip unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - export COMPOSER_ALLOW_SUPERUSER=1
            - composer install --no-dev --ignore-platform-req=ext-*
          artifacts:
            - "**"

      - step:
          name: DDEV Setup and Drupal Check
          services:
            - docker
          caches:
            - docker
          script:
            # Instalacja DDEV
            - curl -L https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash
            
            # Konfiguracja DDEV
            - ddev config --project-type=drupal10 --docroot=web --create-docroot
            
            # Start DDEV
            - ddev start
            
            # Instalacja Drupala
            - ddev composer install
            - ddev drush site:install --account-name=admin --account-pass=admin -y
            
            # Sprawdzenie statusu
            - ddev drush status
            
            # Opcjonalnie: import konfiguracji jeśli potrzebujesz
            # - ddev drush cim -y
            
            # Opcjonalnie: uruchomienie update'ów
            # - ddev drush updb -y

      - parallel:
          steps:
            - step:
                name: CodeSniffer
                image: droptica/phpcs
                script:
                  - phpcs  --standard=./phpcs.xml ./web/modules/custom ./web/themes/custom

            - step:
                name: PHPStan
                image: droptica/phpstan
                script:
                  - ln -s "$(pwd)" /opt/project
                  - phpstan analyse -c ./phpstan.neon --no-progress
