image: drud/ddev:v1.21.5

pipelines:
  default:
    - step:
        name: Uruchamianie DDEV
        services:
          - docker
        script:
          # 1. Uruchomienie środowiska DDEV
          - ddev start
          - ddev exec drush status # Przykład komendy w DDEV

          # 2. Uruchomienie testów automatycznych
          - ddev exec vendor/bin/codecept run
definitions:
  services:
    docker:
      memory: 4096