#!/usr/bin/env bash

PHPCS_STANDARD="./phpcs.xml"
docker run --pull always --rm -t -v `pwd`:/app droptica/phpcs:latest phpcs  --standard=${PHPCS_STANDARD}

PHPCS_STANDARD_TESTS=PSR12
PHPCS_DIRECTORIES_TESTS="/app/tests"
docker run --pull always --rm -t -v `pwd`:/app droptica/phpcs:latest phpcs  --standard=${PHPCS_STANDARD_TESTS} --extensions=php,yml --report=full,gitblame ${PHPCS_DIRECTORIES_TESTS}
