name: Drupal coding standards

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  phpcs:
    name: "Verify Drupal coding standards"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --no-scripts --no-progress

      - name: Run Code sniffer
        run: vendor/bin/phpcs --standard=phpcs.xml
