name: Drupal coding standards

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  phpcs:
    name: "Verify Drupal coding standards"

    runs-on: ubuntu-latest
    container: droptica/phpcs

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important!

      - run: vendor/bin/phpcs --standard=phpcs.xml
