name: Drupal coding standards

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
#  Verify:
#    name: "Verify Drupal coding standards"
#
#    runs-on: ubuntu-latest
#    container: droptica/phpcs
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Verify coding standards
#        run: phpcs  --standard=../../phpcs.xml ./web/modules/custom ./web/themes/custom
  phpcs:
    runs-on: ubuntu-latest
    container: droptica/phpcs

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - uses: thenabeel/action-phpcs@v8
        with:
          phpcs_path: php phpcs.phar
          standard: ../../phpcs.xml
