name: Drupal coding standards

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  phpcs:
    name: "Verify Drupal coding standards"

    runs-on: ubuntu-latest
    container: droptica/phpcs

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important!

      - name: Copy phpcs.xml to container
        run: docker cp ./phpcs.xml $(docker ps -q -f "ancestor=droptica/phpcs"):/ruleset.xml

      - name: Run PHP CodeSniffer
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/web \
            droptica/phpcs \
            phpcs --standard=/ruleset.xml
